language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t astelware/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true astelware/docker-react npm run test
