sudo: required
services:
  - docker
  
before_install:
  - docker build -t astelware/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true astelware/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-436021390624"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
